data:
  _target_: src.datamodules.VOC
  data_dir: data
  batch_size: 16
  num_workers: 16
  download: False
  train_transforms:
    Resize:
      height: 512
      width: 512
    ToTensor: { }

  val_transforms:
    Resize:
      height: 512
      width: 512
    ToTensor: { }

task:
  _target_: src.tasks.TorchvisionRCNNTask

  model:
    _target_: torchvision.models.detection.fasterrcnn_resnet50_fpn
    num_classes: 21  # 20 from pascal + 0th class for background
    progress: False
    pretrained_backbone: True

  optimizer:
    _target_: torch.optim.Adam

  metric:
    _target_: src.metrics.ExactMAPAtThreshold
    num_classes: 21

trainer:
  limit_val_batches: 10
  log_every_n_steps: 1
  gpus: 1

logger:
  project: test
  entity: distilling-object-detectors

checkpoint: {}